export const columns = [
  { name: 'NAME', uid: 'name' },
  { name: 'ROLE', uid: 'role' },
  { name: 'STATUS', uid: 'status' },
  { name: 'ACTIONS', uid: 'actions' },
];
export const users = [
  {
    id: 1,
    name: 'Andrés Carvajal',
    role: 'CEO',
    team: 'Management',
    status: 'active',
    age: '29',
    avatar: 'https://i.pravatar.cc/300',
    email: 'acarvajal@uandresbello.edu',
  },
  {
    id: 2,
    name: 'Julian Delgado',
    role: 'Technical Lead',
    team: 'Development',
    status: 'pausado',
    age: '25',
    avatar: 'https://i.pravatar.cc/300',
    email: 'jdelgado@uandresbello.edu',
  },
  {
    id: 3,
    name: 'Bárbara Farias',
    role: 'Senior Developer',
    team: 'Development',
    status: 'activo',
    age: '22',
    avatar: 'https://i.pravatar.cc/300',
    email: 'bfarias@uandresbello.edu',
  },
  {
    id: 4,
    name: 'Claudio Bellone',
    role: 'Community Manager',
    team: 'Marketing',
    status: 'vacaciones',
    age: '28',
    avatar: 'https://i.pravatar.cc/300',
    email: 'cbellone@uandresbello.edu',
  },
  {
    id: 5,
    name: 'Francisca Martinez',
    role: 'Sales Manager',
    team: 'Sales',
    status: 'activo',
    age: '24',
    avatar: 'https://i.pravatar.cc/300',
    email: 'fmartinez@uandresbello.edu',
  },
  {
    id: 6,
    name: 'Gaspar Carvajal',
    role: 'CEO',
    team: 'Management',
    status: 'activo',
    age: '29',
    avatar: 'https://i.pravatar.cc/300',
    email: 'gcarvajal@uandresbello.edu',
  },
  {
    id: 10,
    name: 'Sofia Fernández',
    role: 'Sales Manager',
    team: 'Sales',
    status: 'activo',
    age: '24',
    avatar: 'https://i.pravatar.cc/300',
    email: 'sfernandez@uandresbello.edu',
  },
];
